name: Main workflow

on:
  - workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: clone test
        id: clonetest
        uses: ./
        with:
          repositories: |
            kubernetes/ingress-nginx/ | main | k1 | 10
            kubernetes/ingress-nginx/ | main | k2 | 10
            kubernetes/ingress-nginx/ | main | k3 | 10

      - name: clone
        id: clonetest
        uses: ./
        with:
          nocheckout: true
          repositories: |
            kubernetes/ingress-nginx/ | main | k1 | 10
            kubernetes/ingress-nginx/ | main | k2 | 10
            kubernetes/ingress-nginx/ | main | k3 | 10
